sudo: false
language: node_js
node_js:
  - '5.0'
  - '4.0'
  - '0.12'
  - '0.10'
env:
  - NODE_ENV=test
services:
  - memcached
  - mongodb
before_script:
  - sleep 15
  - mongo registry_test --eval 'db.addUser("travis", "test");'
